### ISSUE TITLE
Volume in demo

### ISSUE THREAD

**Issue by trevoz** [Lulu04/OALSoundManager#5]
Nice demo - just a suggestion so that volume works at the start and not just when you move the slider later:

```pascal
procedure TForm1.Button1Click(Sender: TObject);
begin
     if FSound = NIL then exit;
     FSound.Volume.Value := TrackBar1.Position;
     FSound.Play;
     //FSound.Volume.Value := oal_VOLUME_MAX;
end;
 ```            

I was using macOS, so I notice the buttons are too small for the text (auto-size?) 
and the text on the fade in/out affects is cut off too. Cosmetic only - see pic 
attached.

![Screenshot 2019-12-28 at 18 40 44](https://user-images.githubusercontent.com/13196674/71540662-95ec8280-29a1-11ea-9035-9cec6000ddba.png)

**Comment by Lulu04** [comment]
Hello Trevoz, I'm very sorry, I just read your post now... ONE YEAR LATER !!...

**Comment by trevoz** [comment]
No worries!

**Comment by Lulu04** [comment]
I'm not familiar with github... I try to update the demo with bugs fixe like you suggest.
I hope all is right now

**Comment by Lulu04** [comment]
I think all is right now. The volume is now a single value between [0..1]
